[tool.poetry]
name = "defi-arbitrage-bot"
version = "0.1.0"
description = ""
authors = ["andy jiang <andyjiangs13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
web3 = "^6.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
